load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

tf_custom_op_library(
    name = "gather_columns.so",
    srcs = ["gather_columns.cc"],
)

tf_custom_op_library(
    name = "scatter_columns.so",
    srcs = ["scatter_columns.cc"],
)
